---

- name: Fedora workstation post-installation system setup
  hosts: 127.0.0.1
  connection: local

  vars:
    update_forced: true

  pre_tasks:

   - name: Install libselinux-python (ansible requirement)
     dnf: name=libselinux-python state=present

  roles:

   - etckeeper
   - role: users
     users_createhome: false

  tasks:

   - name: Update system
     dnf: name='*' state=latest
     when: update_forced == true

   - name: Install additional packages
     dnf: name={{ item }} state=present
     with_items:
      - vim
      - gvim
      - meld
      - tmux
      - htop
      - vifm
      - lshw
      - acpi
      - wget
      - wipe
      - mc
      - terminator
      - tmuxinator
      - pandoc
      - groovy
      - ipython
      - python3-ipython
      - xmonad
      - xmobar
      - firefox
      - thunderbird
      - keepassx
      - rxvt-unicode
      - ruby
      - ruby-irb
      - thunderbird-enigmail
      - xmlstarlet
      - jq
      - tig
      - gitk
      - mutt
      - pylint
      - graphviz
      - python-ctags
      - epydoc
      - python-requests
      - mercurial
      - darcs
      - fedpkg
      - audacity
      - unoconv
      - git-annex
      - qstardict
      - ShellCheck
      - geeqie
      - units
