---

- name: Fedora workstation post-installation system setup
  hosts: localhost
  connection: local

  pre_tasks:

   - name: Install libselinux-python (ansible requirement)
     dnf: name=libselinux-python state=present

  roles:

   - etckeeper
   - role: fedora-common
     update_forced: true
   - sshd
   - user-root
   - lightdm
   - role: custom-xmonad-desktop
     xscreensaver_lock_username: martin
   - role: users
     do_not_access_home_dir: false
   - role: user-makerpm
     do_not_access_home_dir: false
   - role: workstation
     do_not_access_home_dir: false
