---

- name: Fedora workstation post-installation system setup
  hosts: localhost
  connection: local
  vars:
    etckeeper_enabled: false

  pre_tasks:

   - name: Install libselinux-python (ansible requirement)
     dnf: name=libselinux-python state=present

  roles:

   - role: fedora-common
     update_forced: false
   - sshd
   - user-root
   - lightdm
   - role: custom-xmonad-desktop
     xscreensaver_lock_username: martin
   - role: users
     do_not_access_home_dir: true
   - role: workstation
     do_not_access_home_dir: true
