---
- name: Dev playbook to test new roles
  hosts: localhost
  connection: local

  vars:
    do_not_access_home_dir: true
    firewall_type: firewalld

  roles:
   - TODO

  # tasks:
  #  - name: Reconfigure something
  #    ini_file:
  #      dest=/etc/yum.conf
  #      section=main
  #      option=installonly_limit
  #      value=2
  #      state=present
