---

#
# Local DNS server
#

- name: Enable local DNS server (networkmanager dnsmasq)
  ini_file: dest=/etc/NetworkManager/NetworkManager.conf
            section=main
            option=dns
            value=dnsmasq
            state=present
  notify:
   - restart networkmanager

#
# Additional packages
#

- name: Install additional packages
  dnf: name={{ item }} state=present
  with_items:
   - vim
   - gvim
   - tmux
   - vifm
   - mc
   - htop
   - lshw
   - acpi
   - wget
   - curl
   - wipe
   - ipython
   - python3-ipython
   - pylint
   - python3-pylint
   - python-ctags
   - xmlstarlet
   - jq
   - git
   - git-annex
   - tig
   - gitk
   - meld
   - terminator
   - tmuxinator
   - pandoc
   - groovy
   - xmonad
   - xmobar
   - pmount
   - xloadimage
   - firefox
   - thunderbird
   - thunderbird-enigmail
   - keepassx
   - rxvt-unicode
   - ruby
   - ruby-irb
   - mutt
   - notmuch-mutt
   - abook
   - goobook
   - msmtp
   - offlineimap
   - graphviz
   - epydoc
   - mercurial
   - darcs
   - fedpkg
   - audacity
   - unoconv
   - qstardict
   - libappindicator
   - libappindicator-gtk3
   - xscreensaver
   - pavucontrol
   - geeqie
   - nmap
   - tigervnc
   - ddrescue
   - fbreader
