---

#
# Local DNS server
#

- name: Enable local DNS server (networkmanager dnsmasq)
  ini_file: dest=/etc/NetworkManager/NetworkManager.conf
            section=main
            option=dns
            value=dnsmasq
            state=present
  register: local_dns
  notify:
   - restart networkmanager

- name: Etckeeper commit
  command: etckeeper commit "local DNS server - dnsmasq"
  when: etckeeper_enabled == true and local_dns.changed

#
# Reconfigure iptables
#

- name: Check if firewalld is installed
  shell: rpm -q firewalld
  ignore_errors: true
  register: firewalld_check

# When the system doesn't host libvirt virtual machines or run fail2ban,
# I don't need firewalld.
#
- name: Make sure iptables services are installed
  dnf: name=iptables-services state=installed

- name: Stop and disable firewalld
  service: name=firewalld state=stopped enabled=no
  when: firewalld_check.rc == 0

- name: Start iptables
  service: name={{ item }} state=started
  with_items:
   - iptables
   - ip6tables

- name: Enable iptables
  service: name={{ item }} enabled=yes
  with_items:
   - iptables
   - ip6tables
  register: enable_iptables

- name: Etckeeper commit
  command: etckeeper commit "enable iptables"
  when: etckeeper_enabled == true and enable_iptables.changed

#
# Setup sshd
#

- name: Configure iptables to allow sshd (just to be sure)
  lineinfile: dest=/etc/sysconfig/{{ item }}
              line='-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
              insertbefore='^COMMIT'
              state=present
  register: sshd_iptables
  with_items:
   - iptables
   - ip6tables
  notify:
    - restart iptables

- name: Etckeeper commit
  command: etckeeper commit "iptables - enable sshd"
  when: etckeeper_enabled == true and sshd_iptables.changed

#
# Additional packages
#

- name: Install additional packages
  dnf: name={{ item }} state=present
  with_items:
   - vim
   - gvim
   - tmux
   - vifm
   - mc
   - htop
   - lshw
   - acpi
   - wget
   - curl
   - wipe
   - ipython
   - python3-ipython
   - pylint
   - python3-pylint
   - python-ctags
   - xmlstarlet
   - jq
   - git
   - git-annex
   - tig
   - gitk
   - meld
   - terminator
   - tmuxinator
   - pandoc
   - groovy
   - xmonad
   - xmobar
   - pmount
   - xloadimage
   - firefox
   - thunderbird
   - thunderbird-enigmail
   - keepassx
   - rxvt-unicode
   - ruby
   - ruby-irb
   - mutt
   - notmuch-mutt
   - abook
   - goobook
   - msmtp
   - offlineimap
   - graphviz
   - epydoc
   - mercurial
   - darcs
   - fedpkg
   - audacity
   - unoconv
   - qstardict
   - libappindicator
   - libappindicator-gtk3
   - xscreensaver
   - pavucontrol
   - geeqie
   - nmap
   - tigervnc
   - ddrescue
   - fbreader

#
# Make dnf to ignore kernel package
#

- name: Configure dnf - ignore kernel package
  ini_file: dest=/etc/dnf/dnf.conf
            section=main
            option=exclude
            value=kernel*
            state=present
  register: dnf_config_exclude

- name: Etckeeper commit
  command: etckeeper commit "dnf - exclude kernel packages"
  when: etckeeper_enabled == true and dnf_config_exclude.changed
