---

# based on https://fedoramagazine.org/getting-ansible-working-fedora-23/
# but for local usage only

- name: Install python2-dnf for dnf module
  command: dnf install -y python2-dnf
  when: "'{{ lookup('rpm', 'python2-dnf') }}' == ''"

- name: Install python-firewall for firewalld module
  dnf: name=python-firewall state=present

- name: Install libselinux-python
  dnf: name=libselinux-python state=present
