---

#
# firewalld (fedora default)
#

- name: Install firewalld
  dnf: name=firewalld state=installed
  when: firewall_type == "firewalld"

- name: Start and enable firewalld
  service:
    name=firewalld
    state=started
    enabled=yes
  when: firewall_type == "firewalld"

#
# iptables
#

- name: Install iptables services
  dnf: name=iptables-services state=installed
  when: firewall_type == "iptables"

- name: Stop and disable firewalld
  service:
    name=firewalld
    state=stopped
    enabled=no
  when: firewall_type == "iptables"

- name: Start iptables
  service: name={{ item }} state=started
  with_items:
   - iptables
   - ip6tables
  when: firewall_type == "iptables"

- name: Enable iptables
  service: name={{ item }} enabled=yes
  with_items:
   - iptables
   - ip6tables
  when: firewall_type == "iptables"
