---

#
# Create user accounts
#

- name: Create martin group
  group: name=martin gid=1000 state=present

- name: Create martin account
  user: name=martin
        group=martin
        groups=users
        uid=1000
        home=/home/martin
        createhome={{ do_not_access_home_dir == false }}
        shell=/bin/bash
        comment='Martin B.'
        state=present

- name: Groups for additional user accounts
  group: name={{ item }} state=present
  with_items: "{{ additional_users }}"

- name: Additional user accounts
  user: name={{ item }}
        group={{ item }}
        createhome={{ do_not_access_home_dir == false }}
        shell=/bin/bash
        state=present
  with_items: "{{ additional_users }}"

#
# Shared directory
#

- name: Create shared dir in /home
  file: path=/home/shared state=directory
        owner=root group=users mode=2755
  when: do_not_access_home_dir == false

- name: Create dirs in /home/shared
  file: path=/home/shared/{{ item }} state=directory
        owner=root group=users mode=3775
  when: do_not_access_home_dir == false
  with_items:
   - documentaries
   - images
   - lectures
   - movies
   - music
   - podcast
   - series
