---

- name: Install lightdm packages
  dnf: name={{ item }} state=installed
  with_items:
   - lightdm
   - lightdm-kde
   - light-locker

- name: Disable sddm (fedora 22 default)
  service: name=sddm enabled=no

- name: Enable lightdm
  service: name=lightdm enabled=yes

- name: Stop sddm
  service: name=sddm state=stopped

# may fail, so commenting this out
#- name: Start lightdm
#  service: name=lightdm state=started

- name: Disable guest login
  lineinfile: dest=/etc/lightdm/lightdm.conf
              regexp='^#? ?allow-guest ?='
              line='allow-guest = false'
              state=present

- name: Show manual login box
  lineinfile: dest=/etc/lightdm/lightdm.conf
              regexp='{{ item.exp }}'
              line='{{ item.val }}'
              state=present
  with_items:
   - exp: '^#? ?greeter-hide-users ?='
     val: 'greeter-hide-users = true'
   - exp: '^#? ?greeter-show-manual-login ?='
     val: 'greeter-show-manual-login = true'
