---

- name: Create local unix user group
  group: name={{ login }} gid={{ gid }} state=present

- name: Create local unix user account
  user: name={{ login }}
        group={{ login }}
        uid={{ uid }}
        home=/home/{{ login }}
        createhome=yes
        shell=/bin/bash
        comment={{ gecos }}
        state=present
  register: user_created

- name: Etckeeper commit
  command: etckeeper commit "create new user account"
  when: etckeeper_enabled == true and user_created.changed
